#pragma once


#define MARIO_SMALL_BBOX_WIDTH  38
#define MARIO_SMALL_BBOX_HEIGHT 45


#define MARIO_BIG_BBOX_WIDTH  38
#define MARIO_BIG_BBOX_HEIGHT 81

#define RACCOON_MARIO_BIG_BBOX_WIDTH  62
#define RACCOON_MARIO_BIG_BBOX_HEIGHT 81

#define FIRE_MARIO_BBOX_WIDTH  45
#define FIRE_MARIO_BBOX_HEIGHT 81

#define HAMMER_MARIO_BBOX_WIDTH  45
#define HAMMER_MARIO_BBOX_HEIGHT 81

#define FROG_MARIO_BBOX_WIDTH  45
#define FROG_MARIO_BBOX_HEIGHT 91
#define FROG_MARIO_BBOX_WIDTH_LIE  45
#define FROG_MARIO_BBOX_HEIGHT_LIE 81


#define MARIO_UNTOUCHABLE_TIME 5000

