#pragma once
// ACCELERATION
#define ACCELERATION_Y_GRAVITY			0.0016f
#define ACCELERATION_X_WALK				0.010f 
#define ACCELERATION_FRICTION			0.0045f

// LIMIT
#define VELOCITY_X_MAX					0.24f
#define VELOCITY_X_MIN_FOR_SKID			0.12f

// VELOCITY
#define VELOCITY_X_AFTER_SKID			0.08f


// RATIO
#define MARIO_WALKING_BOOST_RATE		0.7f
//0.1f
#define MARIO_JUMP_SPEED_Y				0.62f
#define MARIO_FLY_SPEED_Y				0.25f

#define MARIO_JUMP_DEFLECT_SPEED		0.2f
#define MARIO_DIE_DEFLECT_SPEED			0.5f
